- name: Pull image
  shell: docker pull fog3.ipv6.enstb.fr:5000/bokeh-metahub

- name: Start Metahub container
  docker:
      name: metahub
      image: fog3.ipv6.enstb.fr:5000/bokeh-metahub
      ports: 5000
      dns: "{{ ip }}"
      state: started
