- name: Pull image
  shell: docker pull fog3.ipv6.enstb.fr:5000/bokeh-metahub
  when: mh_present is defined 

- name: Start Metahub container
  docker:
      name: metahub
      image: fog3.ipv6.enstb.fr:5000/bokeh-metahub
      ports: 5000
      dns: "{{ ip }}"
      state: started
  when: mh_present is defined

- name: Stop Metahub container
  docker:
      name: metahub
      image: fog3.ipv6.enstb.fr:5000/bokeh-metahub
      state: absent
  ignore_errors: yes
  when: mh_present is undefined
