- name: Pull image
  shell: docker pull fog3.ipv6.enstb.fr:5000/bokeh-photohub
  when: ph_present is defined

- name: Start Photohub container
  docker:
      name: photohub
      image: fog3.ipv6.enstb.fr:5000/bokeh-photohub
      ports: 
      - 3000
      - 4001
      dns: "{{ ip }}"
      restart_policy: on-failure
      state: started
  when: ph_present is defined

- name: Stop Photohub container
  docker:
      name: photohub
      image: fog3.ipv6.enstb.fr:5000/bokeh-photohub
      state: absent
  ignore_errors: yes
  when: ph_present is undefined
