- name: Pull image
  shell: docker pull fog3.ipv6.enstb.fr:5000/bokeh-photohub

- name: Start Photohub container
  docker:
      name: photohub
      image: fog3.ipv6.enstb.fr:5000/bokeh-photohub
      ports: 
      - 3000
      - 4001
      dns: "{{ ip }}"
      state: started